name = "Smp 5"
author = "the gang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "885c63d69c460f84e976547360dce6df36ed60b362d64588e32ab4aafcda75e7"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.1"]
