name = "Smp 5"
author = "the gang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8814dbb54ad2e5a3fe68a6fcdfbc6ff9b9fd700ac15b110b28e7be608eee2b8b"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.1"]
